# -*- coding: utf-8 -*-
"""Analise da Covid19 em 2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Zo7vnayUlssDJ7wP_vsJlls4J_vC6np
"""

pip install bar_chart_race

import pandas as pd
import bar_chart_race as bcr

#estaamos lendo um arquivo csv sobre a covid-19
df_covid = pd.read_csv('/content/HIST_PAINEL_COVIDBR_2024_Parte2_05out2024 (1).csv', delimiter=';')

#usamos o metodo head() para visualizar as primeiras colunas para termos uma pequena base do que estamos linndado
df_covid.head()

#Aqui damos o dropna para tirar todos os valores nulos(nan) da coluna muncipio.
df_covid.dropna(subset='municipio', inplace=True)

#Logo em seguida usei o metodo head para visualizar se realmente havia sido retirado o nan de municipio
df_covid.head()

#aqui damos o groupby para agrupar região e data e fizemos a soma dos casos acumulados com o .sum()
df_covid.groupby(["regiao", "data"]).sum()['casosAcumulado']

pd.DataFrame(df_covid.groupby(["regiao", "data"]).sum()['casosAcumulado'])

#o metodo unstack desempilha as regiões e joga elas para a esquerda para virar os indices.
#Usamos o .T para inverter os indices por causa do bar_chart_race(bcr).
#droplevl foi usado para dropar o numero de casos acumulados.
pd.DataFrame(df_covid.groupby(["regiao", "data"]).sum()['casosAcumulado']).unstack().T.droplevel(level=0)

df_covid_bcr = pd.DataFrame(df_covid.groupby(["regiao", "data"]).sum()['casosAcumulado']).unstack().T.droplevel(level=0)

df_covid_bcr

#aqui usamos o metodo do bar_chart_race para mostrar a corrida de barras de casos de covid-19
bcr.bar_chart_race(df_covid_bcr)